// Auto-generated by build.py — do not edit directly
// Re-generate with: python3 viewer/build.py

const experiments = [
  {
    id: `exp01`,
    num: `01`,
    title: `TensorFlow Basics`,
    dataset: `N/A`,
    aim: `To create tensors of various dimensions (scalar, vector, matrix, and higher-order) and perform basic tensor operations such as addition, subtraction, multiplication, division, matrix multiplication, reshaping, and transposition using TensorFlow.`,
    algorithm: [
      `Import TensorFlow library.`,
      `Create tensors of different ranks: scalar (0-D), vector (1-D), matrix (2-D), and higher-order (3-D).`,
      `Perform element-wise arithmetic operations: addition, subtraction, multiplication, division.`,
      `Perform matrix multiplication using tf.matmul.`,
      `Reshape and transpose tensors using tf.reshape and tf.transpose.`,
      `Print the resulting tensors and verify their shapes.`,
    ],
    parts: [
      {
        id: `a`,
        name: `Creating Tensors`,
        file: `experiment-01/exp01a_tensor_creation.py`,
        image: `exp01a_output.png`,
        code: `import tensorflow as tf
import numpy as np

scalar   = tf.constant(42)
vector   = tf.constant([1, 2, 3, 4, 5])
matrix   = tf.constant([[1, 2, 3],
                        [4, 5, 6]])
tensor3d = tf.constant(np.arange(24).reshape(2, 3, 4))

print("Tensor Creation")
print("Scalar  (0-D)  :", scalar.numpy())
print("Vector  (1-D)  :", vector.numpy())
print("Matrix  (2-D)  :\\n", matrix.numpy())
print("3-D Tensor shape :", tensor3d.shape)`,
        result: `Tensors of ranks 0, 1, 2, and 3 were successfully created and their values along with shapes were verified.`,
      },
      {
        id: `b`,
        name: `Element-wise Operations`,
        file: `experiment-01/exp01b_elementwise_ops.py`,
        image: `exp01b_output.png`,
        code: `import tensorflow as tf

a = tf.constant([[1, 2],
                 [3, 4]], dtype=tf.float32)
b = tf.constant([[5, 6],
                 [7, 8]], dtype=tf.float32)

print("Element-wise Operations")
print("a + b :\\n", tf.add(a, b).numpy())
print("a - b :\\n", tf.subtract(a, b).numpy())
print("a * b :\\n", tf.multiply(a, b).numpy())
print("a / b :\\n", tf.divide(a, b).numpy())`,
        result: `Element-wise arithmetic operations were performed successfully on two 2x2 matrices, confirming that TensorFlow applies operations element-by-element.`,
      },
      {
        id: `c`,
        name: `Matrix Multiplication`,
        file: `experiment-01/exp01c_matrix_mul.py`,
        image: `exp01c_output.png`,
        code: `import tensorflow as tf

a = tf.constant([[1, 2],
                 [3, 4]], dtype=tf.float32)
b = tf.constant([[5, 6],
                 [7, 8]], dtype=tf.float32)

print("Matrix Multiplication")
print("a @ b :\\n", tf.matmul(a, b).numpy())`,
        result: `Matrix multiplication using tf.matmul produced the correct dot product of the two matrices.`,
      },
      {
        id: `d`,
        name: `Reshape and Transpose`,
        file: `experiment-01/exp01d_reshape_transpose.py`,
        image: `exp01d_output.png`,
        code: `import tensorflow as tf

vector   = tf.constant([1, 2, 3, 4, 5])
matrix   = tf.constant([[1, 2, 3],
                        [4, 5, 6]])

print("Reshape and Transpose")
reshaped   = tf.reshape(vector, [5, 1])
transposed = tf.transpose(matrix)
print("Reshaped (5,1) :\\n", reshaped.numpy())
print("Transposed    :\\n", transposed.numpy())`,
        result: `The vector was reshaped from shape (5,) to (5, 1) and the matrix was transposed from (2, 3) to (3, 2) successfully.`,
      },
    ],
  },
  {
    id: `exp02`,
    num: `02`,
    title: `Perceptron — Iris`,
    dataset: `Iris`,
    aim: `To design and implement a single unit perceptron from scratch using TensorFlow for binary classification of the Iris dataset without using predefined models.`,
    algorithm: [
      `Load the Iris dataset and extract features and labels.`,
      `Convert the multi-class labels to binary (Setosa vs non-Setosa).`,
      `Split the dataset into training and testing sets.`,
      `Standardize the features using StandardScaler.`,
      `Initialize weight vector and bias as TensorFlow Variables.`,
      `Define the perceptron forward pass: weighted sum followed by sigmoid activation.`,
      `Train using binary cross-entropy loss and gradient descent for 50 epochs.`,
      `Compute accuracy on training and testing sets.`,
      `Make predictions on test samples and display results.`,
    ],
    parts: [
      {
        id: ``,
        name: `Perceptron from Scratch`,
        file: `experiment-02/exp02_perceptron_iris.py`,
        image: `exp02_output.png`,
        code: `import tensorflow as tf
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# --- step 1: load the iris dataset ---
data = load_iris()
X = data.data       # 150 samples, 4 features each
y = data.target     # 0 = setosa, 1 = versicolor, 2 = virginica

# make it binary: 1 if setosa, 0 otherwise
y = (y == 0).astype(int)

# --- step 2: split into train and test ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- step 3: normalize features (zero mean, unit variance) ---
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# --- step 4: convert to tensorflow tensors ---
X_train = tf.constant(X_train, dtype=tf.float32)
y_train = tf.constant(y_train, dtype=tf.float32)
y_train = tf.reshape(y_train, [-1, 1])
X_test = tf.constant(X_test, dtype=tf.float32)
y_test = tf.constant(y_test, dtype=tf.float32)
y_test = tf.reshape(y_test, [-1, 1])

# --- step 5: initialize one weight per feature + one bias ---
w = tf.Variable(tf.random.normal([4, 1], stddev=0.1))
b = tf.Variable(tf.zeros([1]))

# --- step 6: define the perceptron model ---
def perceptron(x):
    # y = sigmoid(x1*w1 + x2*w2 + x3*w3 + x4*w4 + b)
    z = tf.matmul(x, w) + b
    return tf.sigmoid(z)

# --- step 7: training loop ---
optimizer = tf.optimizers.SGD(learning_rate=0.1)

for epoch in range(50):
    with tf.GradientTape() as tape:
        y_pred = perceptron(X_train)
        # binary cross-entropy loss
        loss = -tf.reduce_mean(
            y_train * tf.math.log(y_pred + 1e-7) +
            (1 - y_train) * tf.math.log(1 - y_pred + 1e-7)
        )
    grads = tape.gradient(loss, [w, b])
    optimizer.apply_gradients(zip(grads, [w, b]))

    if epoch % 10 == 0:
        predicted = tf.cast(y_pred > 0.5, tf.float32)
        acc = tf.reduce_mean(tf.cast(predicted == y_train, tf.float32))
        print(f"epoch {epoch:3d}  loss {loss.numpy():.4f}  acc {acc.numpy():.4f}")

# --- step 8: evaluate on test data ---
y_test_pred = tf.cast(perceptron(X_test) > 0.5, tf.float32)
test_acc = tf.reduce_mean(tf.cast(y_test_pred == y_test, tf.float32))
print(f"\\ntest accuracy: {test_acc.numpy():.4f}")

# --- step 9: show sample predictions ---
print("\\nsample predictions (first 5 test samples):")
for i in range(5):
    pred = int(y_test_pred[i].numpy())
    actual = int(y_test[i].numpy())
    print(f"  sample {i+1}: predicted {pred}, actual {actual}  {'✓' if pred == actual else '✗'}")`,
        result: `A single unit perceptron was successfully implemented from scratch using TensorFlow. The model classified Iris Setosa vs non-Setosa with high accuracy after 50 epochs of training using binary cross-entropy loss and SGD optimizer.`,
      },
    ],
  },
  {
    id: `exp03`,
    num: `03`,
    title: `MLP — Activations & Optimizers`,
    dataset: `Breast Cancer Wisconsin`,
    aim: `To design, train and test a Multi-Layer Perceptron (MLP) on tabular data and compare the performance of different activation functions and optimizers using TensorFlow/Keras.`,
    algorithm: [
      `Load the Breast Cancer Wisconsin dataset from sklearn.datasets.`,
      `One-hot encode the labels (2 classes: malignant / benign).`,
      `Split data into training and testing sets.`,
      `Normalize the features using StandardScaler.`,
      `Build an MLP with two hidden layers (8 neurons each) using TensorFlow/Keras Sequential API.`,
      `Train the MLP with ReLU, tanh, and sigmoid activation functions using Adam optimizer.`,
      `Train the MLP with Adam, SGD, and RMSprop optimizers using ReLU activation.`,
      `Evaluate test accuracy for each configuration and compare results.`,
    ],
    parts: [
      {
        id: ``,
        name: `MLP Comparison`,
        file: `experiment-03/exp03_mlp_activations_optimizers.py`,
        image: `exp03_output.png`,
        code: `import tensorflow as tf
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# --- step 1: load dataset ---
data = load_breast_cancer()
X = data.data
y = tf.keras.utils.to_categorical(data.target, num_classes=2)

# --- step 2: train-test split ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- step 3: normalize ---
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# --- step 4: build mlp ---
def build_model(activation='relu', optimizer='adam'):
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(8, activation=activation,
                              input_shape=(30,)),
        tf.keras.layers.Dense(8, activation=activation),
        tf.keras.layers.Dense(2, activation='softmax')
    ])
    model.compile(
        optimizer=optimizer,
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# --- step 5: compare activation functions ---
activations = ['relu', 'tanh', 'sigmoid']
print("comparing activation functions (adam):")
print("-" * 35)
for act in activations:
    model = build_model(activation=act, optimizer='adam')
    model.fit(X_train, y_train, epochs=50, verbose=0,
              validation_split=0.1)
    _, acc = model.evaluate(X_test, y_test, verbose=0)
    print(f"  {act:8s}  test accuracy: {acc:.4f}")

# --- step 6: compare optimizers ---
optimizers = ['adam', 'sgd', 'rmsprop']
print("\\ncomparing optimizers (relu activation):")
print("-" * 35)
for opt in optimizers:
    model = build_model(activation='relu', optimizer=opt)
    model.fit(X_train, y_train, epochs=50, verbose=0,
              validation_split=0.1)
    _, acc = model.evaluate(X_test, y_test, verbose=0)
    print(f"  {opt:8s}  test accuracy: {acc:.4f}")`,
        result: `An MLP with two hidden layers was successfully trained on the Breast Cancer Wisconsin dataset. The performance of different activation functions (ReLU, tanh, sigmoid) and optimizers (Adam, SGD, RMSprop) was compared, demonstrating consistent accuracy above 95% for this binary classification task.`,
      },
    ],
  },
  {
    id: `exp04`,
    num: `04`,
    title: `MLP — Fashion MNIST`,
    dataset: `Fashion-MNIST`,
    aim: `To design and implement an MLP to classify 28x28 grayscale fashion images using TensorFlow/Keras and evaluate classification accuracy.`,
    algorithm: [
      `Load the Fashion-MNIST dataset (60,000 training and 10,000 test 28x28 grayscale images, 10 classes).`,
      `Combine the training and test sets into a single dataset.`,
      `Split the data into training (80%) and testing (20%) sets.`,
      `Normalize pixel values to [0, 1] and flatten each image into a 784-dimensional vector.`,
      `One-hot encode the labels (10 classes).`,
      `Build an MLP with two hidden layers (512 and 256 neurons, ReLU) and a softmax output layer.`,
      `Train the model using Adam optimizer and categorical cross-entropy loss for 20 epochs.`,
      `Evaluate the model on the test set and report accuracy.`,
    ],
    parts: [
      {
        id: ``,
        name: `MLP Classifier`,
        file: `experiment-04/exp04_mlp_32x32.py`,
        image: `exp04_output.png`,
        code: `import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split

# --- step 1: load fashion_mnist dataset ---
fashion_mnist = tf.keras.datasets.fashion_mnist
(x_train_full, y_train_full), (x_test_full, y_test_full) = fashion_mnist.load_data()

# --- step 2: combine into single dataset ---
X = np.concatenate([x_train_full, x_test_full], axis=0)
y = np.concatenate([y_train_full, y_test_full], axis=0)

# --- step 3: train-test split ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- step 4: normalize and flatten ---
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0
X_train = X_train.reshape(-1, 28 * 28)
X_test = X_test.reshape(-1, 28 * 28)

# --- step 5: one-hot encode labels (10 classes) ---
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

# --- step 6: build mlp ---
model = tf.keras.Sequential([
    tf.keras.layers.Dense(512, activation='relu', input_shape=(784,)),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# --- step 7: train ---
history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_test, y_test),
    verbose=1
)

# --- step 8: evaluate ---
_, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\\ntest accuracy: {test_acc:.4f}")`,
        result: `An MLP with two hidden layers was trained on the Fashion-MNIST dataset. The model achieved strong classification accuracy on 28x28 grayscale fashion images across 10 categories.`,
      },
    ],
  },
  {
    id: `exp05`,
    num: `05`,
    title: `CNN — TF Flowers`,
    dataset: `TF Flowers`,
    aim: `To design and implement a CNN model to classify multi-category JPG images using TensorFlow/Keras and evaluate accuracy with prediction on new images.`,
    algorithm: [
      `Load the TF Flowers dataset using TensorFlow Datasets (5 categories: daisy, dandelion, roses, sunflowers, tulips).`,
      `Resize images to 128x128, normalize to [0, 1], convert to NumPy arrays, and one-hot encode labels.`,
      `Split the data into training (80%) and testing (20%) sets.`,
      `Build a CNN with three convolutional layers (32, 64, 128 filters) each followed by max-pooling, then a softmax output with 5 units.`,
      `Train the model for 10 epochs with a batch size of 32.`,
      `Evaluate accuracy on the test set.`,
      `Predict the label for a new image and display the predicted flower category.`,
    ],
    parts: [
      {
        id: ``,
        name: `CNN Classifier`,
        file: `experiment-05/exp05_cnn_tf_flowers.py`,
        image: `exp05_output.png`,
        code: `import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
from sklearn.model_selection import train_test_split

# --- step 1: load tf_flowers dataset ---
IMG_SIZE = 128
NUM_CLASSES = 5
CLASS_NAMES = ['daisy', 'dandelion', 'roses', 'sunflowers', 'tulips']

dataset = tfds.load('tf_flowers', as_supervised=True)
train_data = dataset['train']

# --- step 2: resize, normalize, convert to numpy ---
X, y = [], []
for image, label in train_data:
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = tf.cast(image, tf.float32) / 255.0
    X.append(image.numpy())
    y.append(label.numpy())
X = np.array(X)
y = np.array(y)

# one-hot encode labels (5 classes)
y = tf.keras.utils.to_categorical(y, num_classes=NUM_CLASSES)

# --- step 3: train-test split ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- step 4: build cnn ---
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu',
                           input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# --- step 5: train ---
model.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

# --- step 6: evaluate ---
_, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\\ntest accuracy: {test_acc:.4f}")

# --- step 7: predict on a new image ---
preds = model.predict(X_test[:1])
pred_class = CLASS_NAMES[np.argmax(preds[0])]
actual_class = CLASS_NAMES[np.argmax(y_test[0])]
print(f"predicted: {pred_class:12s}")
print(f"actual:    {actual_class:12s}")`,
        result: `A CNN with three convolutional layers was successfully trained on the TF Flowers dataset. The model classified 5 flower categories (daisy, dandelion, roses, sunflowers, tulips) with good accuracy and correctly predicted labels for new images.`,
      },
    ],
  },
  {
    id: `exp06`,
    num: `06`,
    title: `CNN — Overfitting & Underfitting`,
    dataset: `MNIST`,
    aim: `To design and implement CNN models on the MNIST dataset to demonstrate overfitting, underfitting, and how regularization techniques (BatchNormalization, Dropout, data augmentation) fix overfitting.`,
    algorithm: [
      `Load the MNIST dataset (10 digit classes, 28x28 grayscale images).`,
      `Reshape images to 28x28x1, normalize to [0, 1], and one-hot encode labels.`,
      `6a (Overfit): Deep CNN with 3 conv layers (128, 256, 512 filters) and dense layer with no regularization.`,
      `6b (Underfit): Shallow CNN with a single 8-filter conv layer and global average pooling.`,
      `6c (Fixed): Deep CNN as 6a but with BatchNormalization, Dropout, and data augmentation.`,
      `Compare the three approaches to understand overfitting, underfitting, and regularization.`,
    ],
    parts: [
      {
        id: `a`,
        name: `Overfitting`,
        file: `experiment-06/exp06a_overfit.py`,
        image: `exp06a_output.png`,
        code: `import tensorflow as tf

IMG_SIZE, NUM_CLASSES = 28, 10

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0
x_test  = x_test .reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0

y_train = tf.keras.utils.to_categorical(y_train, NUM_CLASSES)
y_test  = tf.keras.utils.to_categorical(y_test,  NUM_CLASSES)

print(f"Train: {x_train.shape[0]}, Test: {x_test.shape[0]}")
print("=" * 60)

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(128, 3, activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 1)),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(256, 3, activation='relu'), tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(512, 3, activation='relu'), tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(), tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')
], name='Overfit')
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print(f"\\n{'=' * 60}")
print("  Overfit model (deep, no regularization)")
print(f"{'=' * 60}")
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test), verbose=1)

_, acc = model.evaluate(x_test, y_test, verbose=0)
print(f"test accuracy: {acc:.4f}")`,
        result: `The deep CNN without any regularization achieved high training accuracy but significantly lower validation accuracy, confirming overfitting. The model memorized the training data rather than learning generalizable features.`,
      },
      {
        id: `b`,
        name: `Underfitting`,
        file: `experiment-06/exp06b_underfit.py`,
        image: `exp06b_output.png`,
        code: `import tensorflow as tf

IMG_SIZE, NUM_CLASSES = 28, 10

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0
x_test  = x_test .reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0

y_train = tf.keras.utils.to_categorical(y_train, NUM_CLASSES)
y_test  = tf.keras.utils.to_categorical(y_test,  NUM_CLASSES)

print(f"Train: {x_train.shape[0]}, Test: {x_test.shape[0]}")
print("=" * 60)

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(8, 3, activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 1)),
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')
], name='Underfit')
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print(f"\\n{'=' * 60}")
print("  Underfit model (shallow, single conv 8 filters)")
print(f"{'=' * 60}")
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test), verbose=1)

_, acc = model.evaluate(x_test, y_test, verbose=0)
print(f"test accuracy: {acc:.4f}")`,
        result: `The shallow CNN with only 8 filters and a single convolutional layer performed poorly on both training and validation sets, confirming underfitting. The model lacks the capacity needed to learn meaningful features from the digit images.`,
      },
      {
        id: `c`,
        name: `Regularized (Fixed)`,
        file: `experiment-06/exp06c_fixed.py`,
        image: `exp06c_output.png`,
        code: `import tensorflow as tf

IMG_SIZE, NUM_CLASSES = 28, 10

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0
x_test  = x_test .reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0

y_train = tf.keras.utils.to_categorical(y_train, NUM_CLASSES)
y_test  = tf.keras.utils.to_categorical(y_test,  NUM_CLASSES)

print(f"Train: {x_train.shape[0]}, Test: {x_test.shape[0]}")
print("=" * 60)

data_aug = tf.keras.Sequential([
    tf.keras.layers.RandomRotation(0.1),
    tf.keras.layers.RandomZoom(0.1),
])

model = tf.keras.Sequential([
    data_aug,
    tf.keras.layers.Conv2D(128, 3, activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 1)),
    tf.keras.layers.BatchNormalization(), tf.keras.layers.MaxPooling2D(), tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Conv2D(256, 3, activation='relu'),
    tf.keras.layers.BatchNormalization(), tf.keras.layers.MaxPooling2D(), tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Conv2D(512, 3, activation='relu'),
    tf.keras.layers.BatchNormalization(), tf.keras.layers.MaxPooling2D(), tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Flatten(), tf.keras.layers.Dense(256, activation='relu'), tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')
], name='Fixed')
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print(f"\\n{'=' * 60}")
print("  Fixed model (BatchNorm + Dropout + augmentation)")
print(f"{'=' * 60}")
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test), verbose=1)

_, acc = model.evaluate(x_test, y_test, verbose=0)
print(f"test accuracy: {acc:.4f}")`,
        result: `The fixed CNN with BatchNormalization, Dropout, and data augmentation achieved balanced training and validation performance. The regularization techniques effectively prevented overfitting while the increased capacity avoided underfitting.`,
      },
    ],
  },
  {
    id: `exp07`,
    num: `07`,
    title: `CNN — Architectures (LeNet / AlexNet / VGG)`,
    dataset: `MNIST`,
    aim: `To implement and compare classic CNN architectures — LeNet-5, AlexNet, and VGG — for multi-class image classification on the MNIST dataset using TensorFlow/Keras.`,
    algorithm: [
      `Load the MNIST dataset and preprocess (reshape, normalize, one-hot encode).`,
      `7a (LeNet-5): Two 5x5 conv layers (6, 16 filters, tanh), average pooling, three dense layers (120, 84, 10). Train 5 epochs.`,
      `7b (AlexNet): Five 3x3 conv layers (32, 64, 128, 128, 64 filters, ReLU), max pooling, dense layers with dropout. Train 5 epochs.`,
      `7c (VGG): Six 3x3 conv layers (64, 64, 128, 128, 256, 256 filters, ReLU), max pooling after every two convs, dense layers with dropout. Train 5 epochs.`,
      `Use Adam optimizer and categorical cross-entropy loss for all three.`,
      `Compare parameter counts and test accuracies across the architectures.`,
    ],
    parts: [
      {
        id: `a`,
        name: `LeNet-5`,
        file: `experiment-07/exp07a_lenet.py`,
        image: `exp07a_output.png`,
        code: `import tensorflow as tf

IMG_SIZE, NUM_CLASSES = 28, 10

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0
x_test  = x_test .reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0

y_train = tf.keras.utils.to_categorical(y_train, NUM_CLASSES)
y_test  = tf.keras.utils.to_categorical(y_test,  NUM_CLASSES)

print(f"Train: {x_train.shape[0]}, Test: {x_test.shape[0]}")
print("=" * 60)

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(6, 5, activation='tanh', input_shape=(IMG_SIZE, IMG_SIZE, 1)),
    tf.keras.layers.AveragePooling2D(pool_size=2),
    tf.keras.layers.Conv2D(16, 5, activation='tanh'),
    tf.keras.layers.AveragePooling2D(pool_size=2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(120, activation='tanh'),
    tf.keras.layers.Dense(84, activation='tanh'),
    tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')
], name='LeNet-5')
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

params = model.count_params()
print(f"\\n{'=' * 60}")
print(f"  LeNet-5 — Parameters: {params:,}")
print(f"{'=' * 60}")
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test), verbose=1)

_, acc = model.evaluate(x_test, y_test, verbose=0)
print(f"test accuracy: {acc:.4f}")`,
        result: `LeNet-5, the smallest architecture with approximately 60K parameters, achieved reasonable accuracy on MNIST using tanh activations and average pooling. Its simple structure makes it fast to train but limits capacity compared to deeper networks.`,
      },
      {
        id: `b`,
        name: `AlexNet`,
        file: `experiment-07/exp07b_alexnet.py`,
        image: `exp07b_output.png`,
        code: `import tensorflow as tf

IMG_SIZE, NUM_CLASSES = 28, 10

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0
x_test  = x_test .reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0

y_train = tf.keras.utils.to_categorical(y_train, NUM_CLASSES)
y_test  = tf.keras.utils.to_categorical(y_test,  NUM_CLASSES)

print(f"Train: {x_train.shape[0]}, Test: {x_test.shape[0]}")
print("=" * 60)

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, 3, activation='relu', padding='same', input_shape=(IMG_SIZE, IMG_SIZE, 1)),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(64, 3, activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(128, 3, activation='relu', padding='same'),
    tf.keras.layers.Conv2D(128, 3, activation='relu', padding='same'),
    tf.keras.layers.Conv2D(64, 3, activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'), tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(256, activation='relu'), tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')
], name='AlexNet')
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

params = model.count_params()
print(f"\\n{'=' * 60}")
print(f"  AlexNet — Parameters: {params:,}")
print(f"{'=' * 60}")
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test), verbose=1)

_, acc = model.evaluate(x_test, y_test, verbose=0)
print(f"test accuracy: {acc:.4f}")`,
        result: `AlexNet, with its deeper structure (five convolutional layers), ReLU activations, max pooling, and dropout regularization, achieved higher accuracy than LeNet-5. The increased depth and parameter count allowed it to learn more complex features.`,
      },
      {
        id: `c`,
        name: `VGG`,
        file: `experiment-07/exp07c_vgg.py`,
        image: `exp07c_output.png`,
        code: `import tensorflow as tf

IMG_SIZE, NUM_CLASSES = 28, 10

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0
x_test  = x_test .reshape(-1, IMG_SIZE, IMG_SIZE, 1).astype('float32') / 255.0

y_train = tf.keras.utils.to_categorical(y_train, NUM_CLASSES)
y_test  = tf.keras.utils.to_categorical(y_test,  NUM_CLASSES)

print(f"Train: {x_train.shape[0]}, Test: {x_test.shape[0]}")
print("=" * 60)

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(64, 3, activation='relu', padding='same', input_shape=(IMG_SIZE, IMG_SIZE, 1)),
    tf.keras.layers.Conv2D(64, 3, activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(128, 3, activation='relu', padding='same'),
    tf.keras.layers.Conv2D(128, 3, activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(256, 3, activation='relu', padding='same'),
    tf.keras.layers.Conv2D(256, 3, activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'), tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(256, activation='relu'), tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')
], name='VGG')
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

params = model.count_params()
print(f"\\n{'=' * 60}")
print(f"  VGG — Parameters: {params:,}")
print(f"{'=' * 60}")
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test), verbose=1)

_, acc = model.evaluate(x_test, y_test, verbose=0)
print(f"test accuracy: {acc:.4f}")`,
        result: `VGG, with six convolutional layers stacked in pairs with max pooling, achieved the highest accuracy due to its greater depth. The use of small 3x3 filters throughout makes it parameter-efficient while allowing deeper feature extraction.`,
      },
    ],
  },
  {
    id: `exp08`,
    num: `08`,
    title: `Simple RNN — IMDB`,
    dataset: `IMDB`,
    aim: `To design and implement a Simple RNN model for binary sentiment classification on the IMDB movie review dataset using TensorFlow/Keras.`,
    algorithm: [
      `Load the IMDB dataset from tf.keras.datasets.imdb with the top 10,000 most frequent words.`,
      `Pad each review to a fixed length of 500 tokens using pad_sequences.`,
      `Build a Sequential model with Embedding (10000 vocab, 128 dim), SimpleRNN (128 units), and Dense (1 unit, sigmoid).`,
      `Compile using Adam optimizer and binary cross-entropy loss.`,
      `Train for 5 epochs with batch size 64 and 20% validation split.`,
      `Evaluate on the test set and print test accuracy.`,
    ],
    parts: [
      {
        id: ``,
        name: `Simple RNN`,
        file: `experiment-08/exp08_simple_rnn.py`,
        image: `exp08_output.png`,
        code: `import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

NUM_WORDS = 10000
MAXLEN = 500

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=NUM_WORDS)

x_train = pad_sequences(x_train, maxlen=MAXLEN)
x_test = pad_sequences(x_test, maxlen=MAXLEN)

model = Sequential([
    Embedding(NUM_WORDS, 128),
    SimpleRNN(128),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

model.fit(
    x_train, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2,
    verbose=1
)

_, test_acc = model.evaluate(x_test, y_test, verbose=0)
print(f"\\nTest accuracy: {test_acc:.4f}")`,
        result: `A Simple RNN model was implemented for binary sentiment classification on the IMDB dataset. The model used an embedding layer followed by a SimpleRNN layer and achieved a reasonable test accuracy, demonstrating the effectiveness of recurrent neural networks for sequence-based text classification tasks.`,
      },
    ],
  },
  {
    id: `exp09`,
    num: `09`,
    title: `LSTM — IMDB`,
    dataset: `IMDB`,
    aim: `To design and implement an LSTM model for binary sentiment classification on the IMDB movie review dataset using TensorFlow/Keras.`,
    algorithm: [
      `Load the IMDB dataset from tf.keras.datasets.imdb with the top 10,000 most frequent words.`,
      `Pad each review to 500 tokens using pad_sequences.`,
      `Build a Sequential model with Embedding (10000 vocab, 128 dim), LSTM (128 units), and Dense (1 unit, sigmoid).`,
      `Compile using Adam optimizer and binary cross-entropy loss.`,
      `Train for 5 epochs with batch size 64 and 20% validation split.`,
      `Evaluate on the test set and print test accuracy.`,
    ],
    parts: [
      {
        id: ``,
        name: `LSTM`,
        file: `experiment-09/exp09_lstm.py`,
        image: `exp09_output.png`,
        code: `import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

NUM_WORDS = 10000
MAXLEN = 500

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=NUM_WORDS)

x_train = pad_sequences(x_train, maxlen=MAXLEN)
x_test = pad_sequences(x_test, maxlen=MAXLEN)

model = Sequential([
    Embedding(NUM_WORDS, 128),
    LSTM(128),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

model.fit(
    x_train, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2,
    verbose=1
)

_, test_acc = model.evaluate(x_test, y_test, verbose=0)
print(f"\\nTest accuracy: {test_acc:.4f}")`,
        result: `An LSTM model was implemented for binary sentiment classification on the IMDB dataset. The model used an embedding layer followed by an LSTM layer and achieved a strong test accuracy, demonstrating the effectiveness of LSTM networks for capturing sequential dependencies in text classification tasks.`,
      },
    ],
  },
  {
    id: `exp10`,
    num: `10`,
    title: `GRU — IMDB`,
    dataset: `IMDB`,
    aim: `To design and implement a GRU model for binary sentiment classification on the IMDB movie review dataset using TensorFlow/Keras.`,
    algorithm: [
      `Load the IMDB dataset from tf.keras.datasets.imdb with the top 10,000 most frequent words.`,
      `Pad each review to 500 tokens using pad_sequences.`,
      `Build a Sequential model with Embedding (10000 vocab, 128 dim), GRU (128 units), and Dense (1 unit, sigmoid).`,
      `Compile using Adam optimizer and binary cross-entropy loss.`,
      `Train for 5 epochs with batch size 64 and 20% validation split.`,
      `Evaluate on the test set and print test accuracy.`,
    ],
    parts: [
      {
        id: ``,
        name: `GRU`,
        file: `experiment-10/exp10_gru.py`,
        image: `exp10_output.png`,
        code: `import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense

NUM_WORDS = 10000
MAXLEN = 500

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=NUM_WORDS)

x_train = pad_sequences(x_train, maxlen=MAXLEN)
x_test = pad_sequences(x_test, maxlen=MAXLEN)

model = Sequential([
    Embedding(NUM_WORDS, 128),
    GRU(128),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(
    x_train, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2,
    verbose=1
)

_, test_acc = model.evaluate(x_test, y_test, verbose=0)
print(f"\\nTest accuracy: {test_acc:.4f}")`,
        result: `A GRU model was implemented for binary sentiment classification on the IMDB dataset. The model used an embedding layer followed by a GRU layer and achieved a strong test accuracy, demonstrating the effectiveness of gated recurrent units for sequence-based text classification tasks.`,
      },
    ],
  },
  {
    id: `exp11`,
    num: `11`,
    title: `Denoising Autoencoder`,
    dataset: `MNIST`,
    aim: `To design and implement a denoising autoencoder using convolutional layers on the MNIST dataset to remove Gaussian noise from handwritten digit images.`,
    algorithm: [
      `Load the MNIST dataset and normalize pixel values to [0, 1].`,
      `Expand dimensions to add a channel axis (28x28x1).`,
      `Add Gaussian noise (factor 0.5) to training and test images, then clip to [0, 1].`,
      `Build encoder with Conv2D (32, 64 filters) + MaxPooling + bottleneck Conv2D (64).`,
      `Build decoder with UpSampling + Conv2D (64, 32 filters) + final Conv2D (1, sigmoid).`,
      `Compile using Adam optimizer and binary cross-entropy loss.`,
      `Train for 10 epochs with batch size 128, noisy inputs and clean targets.`,
      `Evaluate reconstruction loss on noisy test set and display sample statistics.`,
    ],
    parts: [
      {
        id: ``,
        name: `Convolutional Autoencoder`,
        file: `experiment-11/exp11_autoencoder.py`,
        images: ["exp11_output.png", "exp11_output2.png"],
        code: `import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, UpSampling2D
from tensorflow.keras.models import Sequential
import numpy as np

(x_train, _), (x_test, _) = tf.keras.datasets.mnist.load_data()

x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0
x_train = np.expand_dims(x_train, axis=-1)
x_test = np.expand_dims(x_test, axis=-1)

noise_factor = 0.5
x_train_noisy = x_train + noise_factor * np.random.normal(size=x_train.shape)
x_test_noisy = x_test + noise_factor * np.random.normal(size=x_test.shape)
x_train_noisy = np.clip(x_train_noisy, 0.0, 1.0)
x_test_noisy = np.clip(x_test_noisy, 0.0, 1.0)

autoencoder = Sequential([
    Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(28,28,1)),
    MaxPooling2D((2,2), padding='same'),
    Conv2D(64, (3,3), activation='relu', padding='same'),
    MaxPooling2D((2,2), padding='same'),
    Conv2D(64, (3,3), activation='relu', padding='same'),
    UpSampling2D((2,2)),
    Conv2D(32, (3,3), activation='relu', padding='same'),
    UpSampling2D((2,2)),
    Conv2D(1, (3,3), activation='sigmoid', padding='same')
])

autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

autoencoder.summary()

autoencoder.fit(
    x_train_noisy, x_train,
    epochs=10,
    batch_size=128,
    validation_data=(x_test_noisy, x_test),
    verbose=1
)

test_loss = autoencoder.evaluate(x_test_noisy, x_test, verbose=0)
print(f"\\nTest loss: {test_loss:.4f}")

decoded = autoencoder.predict(x_test_noisy[:10], verbose=0)
print("\\nSample reconstruction (noisy -> denoised):")
for i in range(3):
    print(f"  Sample {i+1}: noisy pixel mean={x_test_noisy[i].mean():.3f}, "
          f"denoised pixel mean={decoded[i].mean():.3f}")`,
        result: `A convolutional denoising autoencoder was successfully implemented on the MNIST dataset. The model learned to remove Gaussian noise from handwritten digit images by compressing the input through a bottleneck and reconstructing a clean output, demonstrating the effectiveness of autoencoders for image denoising tasks.`,
      },
    ],
  },
  {
    id: `exp12`,
    num: `12`,
    title: `GAN — MNIST`,
    dataset: `MNIST`,
    aim: `To design and implement a Generative Adversarial Network (GAN) to generate handwritten digit images on the MNIST dataset using TensorFlow/Keras.`,
    algorithm: [
      `Load the MNIST dataset and normalize pixel values to [0, 1].`,
      `Build the Generator: Dense layers (128, 256, 512, 784 units with ReLU, final Sigmoid) reshaping to 28x28x1.`,
      `Build the Discriminator: Flatten, Dense (512, 256 ReLU), Sigmoid output for real/fake classification.`,
      `Compile Discriminator using Adam (lr=0.0002) and binary cross-entropy loss; freeze it, then create Combined model (Generator -> Discriminator).`,
      `For each epoch: sample random noise, generate fake images, train Discriminator on real (label=1) and fake (label=0) batches.`,
      `Train Generator via Combined model with noise input and valid labels (label=1) to fool the Discriminator.`,
      `Print Discriminator loss/accuracy and Generator loss for each epoch.`,
      `After training, generate 10 sample digits and display pixel mean statistics.`,
    ],
    parts: [
      {
        id: ``,
        name: `GAN`,
        file: `experiment-12/exp12_gan.py`,
        image: `exp12_output.png`,
        code: `import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Reshape
from tensorflow.keras.models import Sequential
import numpy as np

LATENT_DIM = 100

(x_train, _), _ = tf.keras.datasets.mnist.load_data()
x_train = x_train.astype('float32') / 255.0
x_train = np.expand_dims(x_train, axis=-1)

generator = Sequential([
    Dense(128, activation='relu', input_shape=(LATENT_DIM,)),
    Dense(256, activation='relu'),
    Dense(512, activation='relu'),
    Dense(784, activation='sigmoid'),
    Reshape((28, 28, 1))
], name='generator')

discriminator = Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(512, activation='relu'),
    Dense(256, activation='relu'),
    Dense(1, activation='sigmoid')
], name='discriminator')

discriminator.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0002),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

discriminator.trainable = False

gan_input = tf.keras.Input(shape=(LATENT_DIM,))
fake_image = generator(gan_input)
gan_output = discriminator(fake_image)
combined = Sequential([generator, discriminator], name='combined')
combined.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0002),
    loss='binary_crossentropy'
)

batch_size = 128
epochs = 20
half_batch = batch_size // 2

for epoch in range(epochs):
    idx = np.random.randint(0, x_train.shape[0], half_batch)
    real_images = x_train[idx]
    real_labels = np.ones((half_batch, 1))

    noise = np.random.normal(0, 1, (half_batch, LATENT_DIM))
    fake_images = generator.predict(noise, verbose=0)
    fake_labels = np.zeros((half_batch, 1))

    d_loss_real = discriminator.train_on_batch(real_images, real_labels)
    d_loss_fake = discriminator.train_on_batch(fake_images, fake_labels)
    d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

    noise = np.random.normal(0, 1, (batch_size, LATENT_DIM))
    valid_labels = np.ones((batch_size, 1))
    g_loss = combined.train_on_batch(noise, valid_labels)

    print(f"Epoch {epoch+1:2d}/{epochs}  D loss: {d_loss[0]:.4f}  D acc: {d_loss[1]:.4f}  G loss: {g_loss:.4f}")

noise = np.random.normal(0, 1, (10, LATENT_DIM))
generated = generator.predict(noise, verbose=0)
print("\\nGenerated sample pixel means:")
for i in range(10):
    print(f"  Sample {i+1:2d}: mean = {generated[i].mean():.3f}")`,
        result: `A Generative Adversarial Network was implemented on the MNIST dataset. The Generator learned to produce realistic handwritten digit images from random noise, while the Discriminator simultaneously improved at distinguishing real from fake samples. The adversarial training process successfully balanced both networks, demonstrating the effectiveness of GANs for generative image tasks.`,
      },
    ],
  },
];
